# Generated by Django 5.0.6 on 2026-08-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrecord',
            name='period_date',
            field=models.DateField(blank=True, help_text='Any date within the reporting period — used for year-to-date totals.', null=True),
        ),
    ]
