# Generated by Django 5.0.6 on 2026-08-19 08:03

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_beneficiaryrecord_period_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/field_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), apps.core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='projects/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), apps.core.validators.validate_document_size]),
        ),
    ]
