# Generated by Django 5.0.6 on 2026-08-16 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_beneficiaryrecord_period_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_uid', models.CharField(help_text='KoboToolBox form/asset ID', max_length=100)),
                ('submission_id', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed')], default='new', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kobo_submissions', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('form_uid', 'submission_id')},
            },
        ),
    ]
