# Generated by Django 5.2.17 on 2026-08-21 14:02

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='donations/proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), apps.core.validators.validate_document_size]),
        ),
        migrations.AddField(
            model_name='donation',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Proof Rejected')], default='pending', max_length=20),
        ),
    ]
