# Generated by Django 5.0.6 on 2026-08-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hr', 'HR Management'), ('finance', 'Finance'), ('media', 'Media Team'), ('program_manager', 'Program Manager')], max_length=20),
        ),
    ]
