# Generated by Django 5.0.6 on 2026-08-16 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='achievements/thumbnails/')),
                ('youtube_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to the permanent Featured section on the homepage.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first among featured items.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/gallery/')),
                ('youtube_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='achievements.achievement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
