# Generated by Django 5.0.6 on 2026-07-30 20:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cash_ssp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bank_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bank_ssp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('SSP', 'South Sudanese Pound')], max_length=3)),
                ('category', models.CharField(choices=[('capacity_building', 'Capacity Building'), ('radio_programs', 'Radio Programs'), ('school_clubs', 'School Clubs'), ('community_dialogue', 'Community Dialogue'), ('civic_education', 'Civic Education'), ('operational', 'Operational'), ('travel', 'Travel & Transport'), ('procurement', 'Procurement'), ('other', 'Other')], max_length=30)),
                ('reason', models.TextField(help_text='Explain clearly why this money is needed.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Awaiting Finance Review'), ('forwarded', 'Forwarded to Super Admin'), ('info_requested', 'More Information Requested'), ('approved', 'Approved — Awaiting Disbursement'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], default='submitted', max_length=20)),
                ('finance_notes', models.TextField(blank=True)),
                ('super_admin_notes', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_decided', to=settings.AUTH_USER_MODEL)),
                ('executed_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_executed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_forwarded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('account_type', models.CharField(choices=[('cash', 'Cash at Hand'), ('bank', 'In Bank')], max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('SSP', 'South Sudanese Pound')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('income_source', models.CharField(blank=True, choices=[('donor', 'Donor Contribution'), ('grant', 'Grant'), ('partner', 'Partner Funding'), ('membership', 'Membership Fees'), ('other', 'Other')], max_length=20)),
                ('expense_category', models.CharField(blank=True, choices=[('capacity_building', 'Capacity Building'), ('radio_programs', 'Radio Programs'), ('school_clubs', 'School Clubs'), ('community_dialogue', 'Community Dialogue'), ('civic_education', 'Civic Education'), ('operational', 'Operational'), ('travel', 'Travel & Transport'), ('procurement', 'Procurement'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_recorded', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.financialrequest')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
