# Generated by Django 5.0.6 on 2026-08-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are', models.TextField(default='Integrity South Sudan (ISS) is a South Sudanese non-governmental organization founded in 2017 and registered in 2023 with the Relief and Rehabilitation Commission. Headquartered in Juba, ISS is active in Central Equatoria and Western Equatoria States, with planned expansion to Upper Nile and Bahr El Ghazal.')),
                ('mission', models.TextField(blank=True)),
                ('thematic_areas', models.TextField(default='Democracy & Good Governance, Livelihood, Environmental Protection & Climate Change, Media Advocacy, Protection & GBV, and Peace and Security.')),
                ('leadership_note', models.CharField(default='Led by Chief Executive Director Luate Satimon Joel.', max_length=200)),
                ('partners_note', models.TextField(blank=True, help_text='Optional summary — the Partners page already lists them individually.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
