# Generated by Django 5.0.6 on 2026-07-31 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('job_advertisement', 'Job Advertisement'), ('update', 'Update'), ('news', 'News'), ('breaking_news', 'Breaking News'), ('recently_concluded_event', 'Recently Concluded Event'), ('upcoming_event', 'Upcoming Event'), ('international_update', 'International Update')], max_length=30)),
                ('brief_description', models.CharField(help_text='Shown on the landing page feed card.', max_length=300)),
                ('body', models.TextField(help_text='Full detail shown on the article page.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='newsfeed/thumbnails/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube link, used as the feed card preview if no thumbnail.')),
                ('is_published', models.BooleanField(default=True)),
                ('display_until', models.DateField(blank=True, help_text='Leave blank to keep this post visible indefinitely.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsfeed/gallery/')),
                ('youtube_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='newsfeed.newspost')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
