# Generated by Django 5.0.6 on 2026-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='If set and in the future, this post stays hidden until then.', null=True),
        ),
    ]
