# Generated by Django 5.2.17 on 2026-08-26 19:47

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_newsmedia_image_alter_newspost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='document',
            field=models.FileField(blank=True, help_text='Required PDF for Policy Brief/Paper, Press Statement, and Article posts. Shown as a download.', null=True, upload_to='newsfeed/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('job_advertisement', 'Job Advertisement'), ('update', 'Update'), ('news', 'News'), ('breaking_news', 'Breaking News'), ('recently_concluded_event', 'Recently Concluded Event'), ('upcoming_event', 'Upcoming Event'), ('international_update', 'International Update'), ('policy_brief', 'Policy Brief/Paper'), ('press_statement', 'Press Statement'), ('article', 'Article')], max_length=30),
        ),
    ]
