# Generated by Django 5.0.6 on 2026-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Integrity South Sudan', max_length=200)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_general', models.EmailField(blank=True, max_length=254)),
                ('email_media', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed link, optional')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
