# Generated by Django 5.0.6 on 2026-08-19 08:03

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='podcasts/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size]),
        ),
    ]
