# Generated by Django 5.0.6 on 2026-08-17 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('capacity_building', 'Capacity Building'), ('radio_programs', 'Radio Programs (Integrity Hour)'), ('school_clubs', 'School Clubs'), ('community_dialogue', 'Community Dialogue'), ('civic_education', 'Civic Education')], max_length=30)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('sponsors', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='activities/thumbnails/')),
                ('youtube_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/gallery/')),
                ('youtube_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='activities.activity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
