# Generated by Django 5.0.6 on 2026-08-19 08:03

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_library/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip']), apps.core.validators.validate_media_asset_size]),
        ),
    ]
